---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-secrets-manager
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 6d6ebc76-7bbd-42f5-8bc7-78f4fabd5944
    variations:
      - name: security-enforced
        mark_ready: true
        install_type: fullstack
        pre_validation: "tests/scripts/pre-validate.sh solutions/security-enforced"
        post_validation: "tests/scripts/post-validate.sh"
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
          scope_resource_group_var_name: existing_resource_group_name
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        pre_validation: "tests/scripts/pre-validate.sh solutions/fully-configurable"
        post_validation: "tests/scripts/post-validate.sh"
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
          scope_resource_group_var_name: existing_resource_group_name
